# The URL the site will be built for
theme = "DeepThought"
base_url = "http://zhihanz.github.io"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
title = "zhihanz + cloud native"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
[extra]
# Put all your custom variables here
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/docs", name = "Docs" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]},
]
# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "zhihanz"
avatar = "/images/avatar.png"

# Social links
[extra.social]
email = "zzh243402448@gmail.com"
github = "zhihanz"
# keybase = "<keybase_username>"
# linkedin = "<linkedin_username>"
# stackoverflow = "<stackoverflow_userid>"
# twitter = "<twitter_username>"

# To add google analytics
[extra.analytics]
google = "<your_gtag>"

# To add hyvor comments
[extra.commenting]
hyvor = "<your_hyvor_website_id>"

# To enable mapbox maps
[extra.mapbox]
access_token = "<your_access_token>"
